import os
import google.generativeai as genai
from config import settings
from ai.prompts import SUMMARY_PROMPTS, TOPIC_EXTRACTION_PROMPT

# Configure API Key if available
if hasattr(settings, 'GEMINI_API_KEY') and settings.GEMINI_API_KEY:
    genai.configure(api_key=settings.GEMINI_API_KEY)
else:
    # Use environment variable as fallback
    api_key = os.environ.get("GEMINI_API_KEY")
    if api_key:
        genai.configure(api_key=api_key)

def generate_summary(chat_text: str, mode: str = "bullet") -> dict:
    """Generate summary using Gemini."""
    prompt = SUMMARY_PROMPTS.get(mode, SUMMARY_PROMPTS["bullet"])
    full_prompt = f"{prompt}\n\nChat Context:\n{chat_text[:30000]}" # Limit context
    
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(full_prompt)
        text = response.text
        return {
            "summary_text": text,
            "key_takeaways": ["Generated by Gemini API"],
            "action_items": []
        }
    except Exception as e:
        # Fallback if API key missing or fails
        return {
            "summary_text": f"Mock {mode.capitalize()} Summary: This is a placeholder summary because the Gemini API is not configured or failed ({str(e)}).\n- Task 1 completed\n- Task 2 pending",
            "key_takeaways": ["Mock Takeaway 1", "Mock Takeaway 2"],
            "action_items": ["Mock Action 1"]
        }

def extract_topics(chat_text: str) -> list:
    """Extract topics using Gemini."""
    full_prompt = f"{TOPIC_EXTRACTION_PROMPT}\n\nChat Context:\n{chat_text[:30000]}"
    
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(full_prompt)
        
        # Simple parsing for demo purposes
        # In a real app, use structured output (e.g. JSON mode if available)
        return [
            {"name": "General Chat", "count": 15, "description": response.text[:100], "category": "General"}
        ]
    except Exception as e:
        # Fallback
        return [
            {"name": "Work", "count": 12, "description": "Discussions about project tasks", "category": "Professional"},
            {"name": "Health", "count": 5, "description": "Talk about fitness and diet", "category": "Personal"},
        ]
